# Project Euler problem 002.
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

smallvalue = 1
largevalue = 2
sumofeven = 0
fibonacci = 0

while fibonacci < 4000001:
	fibonacci = smallvalue + largevalue
	
	if fibonacci % 2 == 0:
	    sumofeven += fibonacci
	    
	smallvalue = largevalue
	largevalue = fibonacci
	
print "The sum of the even-valued fibonacci number up to 4000000 is: ", sumofeven

